
package me.boujdi.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Convert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://ws.example.org/", className = "me.boujdi.proxy.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://ws.example.org/", className = "me.boujdi.proxy.ConvertResponse")
    @Action(input = "http://ws.example.org/BanqueService/ConvertRequest", output = "http://ws.example.org/BanqueService/ConvertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns me.boujdi.proxy.Compte
     */
    @WebMethod(operationName = "ConsulterCompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConsulterCompte", targetNamespace = "http://ws.example.org/", className = "me.boujdi.proxy.ConsulterCompte")
    @ResponseWrapper(localName = "ConsulterCompteResponse", targetNamespace = "http://ws.example.org/", className = "me.boujdi.proxy.ConsulterCompteResponse")
    @Action(input = "http://ws.example.org/BanqueService/ConsulterCompteRequest", output = "http://ws.example.org/BanqueService/ConsulterCompteResponse")
    public Compte consulterCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<me.boujdi.proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://ws.example.org/", className = "me.boujdi.proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://ws.example.org/", className = "me.boujdi.proxy.ListComptesResponse")
    @Action(input = "http://ws.example.org/BanqueService/listComptesRequest", output = "http://ws.example.org/BanqueService/listComptesResponse")
    public List<Compte> listComptes();

}
